USE master
GO
USE QUANLYGIANGVIEN
GO

CREATE TABLE TAIKHOAN
(
	ID INT IDENTITY NOT NULL,
	MAGV NVARCHAR(20) NOT NULL,
	PASSWD NVARCHAR(50) NOT NULL,
	IS_STATUS BIT NOT NULL,
	CONSTRAINT PK_TAIKHOAN PRIMARY KEY(ID),
	CONSTRAINT FK_TAIKHOAN FOREIGN KEY (MAGV) REFERENCES GIANGVIEN(MAGV)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);
GO

CREATE PROCEDURE SP_LOGIN
	@MAGV NVARCHAR(20),
	@PASSWD NVARCHAR(50)
	AS
	BEGIN
		SELECT *
		FROM TAIKHOAN
		WHERE MAGV=@MAGV AND PASSWD=@PASSWD
	END

CREATE PROCEDURE SP_STATUS
	@MAGV NVARCHAR(20),
	@IS_STATUS BIT
	AS
	BEGIN
		UPDATE TAIKHOAN
		SET IS_STATUS=@IS_STATUS
		WHERE MAGV=@MAGV
	END

CREATE PROCEDURE SP_CHECKSTATUS
	AS
	BEGIN
		SELECT * FROM TAIKHOAN WHERE IS_STATUS = 1;
	END

CREATE PROCEDURE SP_FINDMAGV
	AS
	BEGIN
		SELECT MAGV FROM TAIKHOAN WHERE IS_STATUS = 1
	END